$ANSIBLE_VAULT;1.1;AES256
61313732653464643038616438333639393532643435633964663464633165663532663366313661
3736323837633966653065653166333165613865636362300a383033303730636234373464656234
38336161346639346464396562393832363534643432656162373562323665376637306439643932
6537636566643935340a643865356336343962623532353935643639333036376330643036393761
63636539363961306332633731316535366435623261393466623365336536373066303532376661
33306438643433363734326632336333373961313562303234626565613833383139333238333133
38646165313861616333363964366139396666323363303666626661663139386263383164663334
31623866643631303365333230323236383832393738656135626164333035303333383934333530
63396430396633356539613665336630643133303136333632623633613432396364326334303231
30376162346239316138313331316538366461623061363537313266613233623337613731646534
36336339333864326632363133653037363730623734656233656331313030613561653562356537
30363836396635653863363837383338616238376563626537353230376133616436363662616231
65613534663234346231613435316433313931346562386533623761616137636438386231343966
66376634383732363730626337303238626462623639383531363534646462353564393862343364
37326263316630343439383238393539643139346266323133633934326432646662336136646337
62373462646131323431646435646638343037336537346138346536383661383034363664323738
36616233376566633262336238636364303035383964636366383339633737643934616337303939
32633432353234373334333234333231616562353330353962313861366233316266363038366164
62356630653861313331396265316437643233346339323764383436316363393262323635626665
61353634336539313539313030653064336364333532356138303565666332386435336365646336
66326431643239306137376133616665323764333430336161663336393630393566386237633936
34346431613564383639633261373763333038626232343364626262333632636566316237396432
623238346132383465663266333332353361
