$ANSIBLE_VAULT;1.1;AES256
31363435613735313566363538363939393334663934363231643933386265393730373437656163
3536343138333731323134656331646230343266626239300a613630616566303862303163613335
39313234346662643636313433616535663931363630313733633163333239313963663238393666
3034613431373530390a616162306338313637333061343265653830333639396238373861356636
33323032393937636164366239626365666266396665646466646436633534643536663863376437
38653831313063393939633662373133326463373137616663616134623735353161353162616366
32356365386364633931613730363063353261333539666634373439626166323635643661626461
65663235633037393462306334626638336264333565666434396534376566666635393461623931
35623733633965363736303731363230366631303064653737306661393762633135643534353838
34343162613435626230613465313837333262333566646664633434646533353338333862636336
63633634646239353234656366356564656433303032363337656463383561373130636633636233
62363535373862396131373933643838383832306164353461303061653439633632393766376262
39363334343562393961346637343337303464623530333265333938373966356333393761633465
61333461366531643162623537333633636333626232333536373565303939613932343936366562
33633938343466393636366161343234363337393065666565316230376230656237306237393935
65306633343939646131
